# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{colortail}
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Lubow"]
  s.date = %q{2010-04-21}
  s.default_executable = %q{colortail}
  s.description = %q{Tail a file and color lines based on regular expressions within that line. By setting up multiple expression and color groups in the configuration file, you can apply highlighting to a file while its being tailed.}
  s.email = %q{eric@lubow.org}
  s.executables = ["colortail"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "Changelog.markdown",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "TODO.markdown",
     "VERSION",
     "bin/colortail",
     "colortail.gemspec",
     "examples/colortail.rb",
     "examples/test.log",
     "lib/colortail.rb",
     "lib/colortail/application.rb",
     "lib/colortail/configuration.rb",
     "test/helper.rb",
     "test/test_colortail.rb"
  ]
  s.homepage = %q{http://codaset.com/elubow/colortail}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Tail a file and color lines based on regular expressions within that line}
  s.test_files = [
    "test/helper.rb",
     "test/test_colortail.rb",
     "examples/colortail.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<file-tail>, [">= 0"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<file-tail>, [">= 0"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<file-tail>, [">= 0"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

